#!/usr/bin/env bash

# Keep 1000 lines in .bash_history (default is 500)
export HISTSIZE=1000
export HIST
export OMP_NUM_THREADS=1
export EDITOR=vim
FILESIZE=1000


export PATH=${HOME}/.local/bin:${PATH}
export PATH=${HOME}/bin:${PATH}
if [[ -d ${HOME}/bin/git-annex.linux ]]; then
  export PATH="${HOME}/bin/git-annex.linux":${PATH}
fi
export PATH=${PATH}:~/bin/"${HOSTNAME}"

case $HOSTNAME in
  (CRD-L-05716) source /etc/bash.bashrc;;
  (lapsgs24)
#    source /etc/profile.d/lmod.sh
    export MODULEPATH=/usr/share/lmod/6.6/modulefiles/Core
    export MODULEPATH=${HOME}/modulefiles:${MODULEPATH}
    ;;
  (neon)
    export MODULEPATH=${MODULEPATH}:/data/scratch/jaustar/modulefiles
    #module purge
    #module load preCICE/1.6.0-opt
    #module load cmake/3.12.1
    ;;
  (*)
	;;
esac

case $HOSTNAME in
  (lapsgs24)
    export PS1="\[\033[0;32m\]\u\[\033[0;36m\]@\h:\w\[\033[0;32m\]\$(__git_ps1)\n└─(\[\033[1;32m\]\t, \$(ls -1 | wc -l | sed 's: ::g') files, \$(ls -sh | head -n1 | sed 's/total //')b\[\033[1;37m\]\[\033[0;32m\])\342\224\200>\[\033[0m\] "
    ;;
  (neon | helium | sgscl* | kepler | vgpu | argon* )
    export PS1="\[\033[0;32m\]\u\[\033[0;36m\]@\h:\w\[\033[0;32m\]\$(__git_ps1)\n└─(\[\033[1;32m\]\t, \$(ls -1 | wc -l | sed 's: ::g') files, \$(ls -sh | head -n1 | sed 's/total //')b\[\033[1;37m\]\[\033[0;32m\])\342\224\200>\[\033[0m\] "
    ;;
  (*)
    export PS1="\u\[\033[1;34m\]@\h\[\033[0m\]:\[\033[0;32m\]\w\[\033[0;32m\]\$(__git_ps1)\n└─(\[\033[1;32m\]\t, \$(ls -1 | wc -l | sed 's: ::g') files, \$(ls -sh | head -n1 | sed 's/total //')b\[\033[1;37m\]\[\033[0;32m\])\342\224\200>\[\033[0m\] "
    ;;
esac


# Use gnome-keyring on a desktop session or else run ssh-agent
#This also takes care that only one ssh-agent is running. I don't know if this conflicts with gnome.
#https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent
if [[ ! -z "${DESKTOP_SESSION}" ]];then
    #eval $(gnome-keyring-daemon --start)
#    echo "Starting gnome keyring as we are running a desktop session"
#    echo "Value of DESKTOP_SESSION ${DESKTOP_SESSION}"
#    eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
#    export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
#    dbus-update-activation-environment --systemd DISPLAY
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
    #export SSH_AUTH_SOCK
#  echo "Don't do anything about the ssh keys"
#if [[ ! -z "${DESKTOP_SESSION}" ]];then
#    echo "Starting gnome keyring as we are running a desktop session"
#    export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
#else
#if [ -n "$DESKTOP_SESSION" ];then
#    eval $(gnome-keyring-daemon --start)
#    export SSH_AUTH_SOCK
else
#Start ssh-agent
	if ! pgrep -u "$USER" ssh-agent > /dev/null; then
		  ssh-agent > ~/.ssh-agent-thing
	fi
	if [[ "$SSH_AGENT_PID" == "" ]]; then
		  eval "$(<~/.ssh-agent-thing)"
	fi
fi

# JAVA
# Make Java use anti-aliasing for nicer fonts
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"

# Enable X-forwarding on windows subsystem
case $HOSTNAME in
  (CRD-L-05716) export DISPLAY=127.0.0.1:0
#    export TERM=rxvt-unicode-256color
  ;;
  (*) ;;
esac